# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.11
_src_path: gh:algorandfoundation/algokit-python-template
author_email: my@mail.com
author_name: CiottiGiorgio
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: verifiable-giveaway-contracts

