name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

jobs:
  verifiable-giveaway-contracts-validate:
    name: Run verifiable-giveaway-contracts release
    secrets: inherit
    uses: ./.github/workflows/verifiable-giveaway-contracts-ci.yaml

  verifiable-giveaway-contracts-release:
    name: Run verifiable-giveaway-contracts release
    secrets: inherit
    uses: ./.github/workflows/verifiable-giveaway-contracts-cd.yaml
    needs: verifiable-giveaway-contracts-validate

  verifiable-giveaway-frontend-validate:
    name: Run verifiable-giveaway-frontend release
    secrets: inherit
    uses: ./.github/workflows/verifiable-giveaway-frontend-ci.yaml

  verifiable-giveaway-frontend-release:
    permissions:
      packages: write
    name: Run verifiable-giveaway-frontend release
    secrets: inherit
    uses: ./.github/workflows/verifiable-giveaway-frontend-cd.yaml
    needs: verifiable-giveaway-frontend-validate
