name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'projects/verifiable-giveaway-frontend/**'

permissions:
  contents: read
  packages: read

jobs:
  verifiable-giveaway-frontend-validate:
    name: Run verifiable-giveaway-frontend release
    secrets: inherit
    uses: ./.github/workflows/verifiable-giveaway-frontend-ci.yaml

  verifiable-giveaway-frontend-release:
    permissions:
      packages: write
    name: Run verifiable-giveaway-frontend release
    secrets: inherit
    uses: ./.github/workflows/verifiable-giveaway-frontend-cd.yaml
    needs: verifiable-giveaway-frontend-validate
