name: Pull Request validation

on:
  pull_request:
    paths:
      - "projects/verifiable-giveaway-contracts/**"


jobs:
  verifiable-giveaway-contracts-ci:
    name: Run verifiable-giveaway-contracts validation
    uses: ./.github/workflows/verifiable-giveaway-contracts-ci.yaml
