name: Pull Request validation

on: [pull_request]


jobs:
  verifiable-giveaway-contracts-ci:
    name: Run verifiable-giveaway-contracts validation
    uses: ./.github/workflows/verifiable-giveaway-contracts-ci.yaml

  verifiable-giveaway-frontend-ci:
    name: Run verifiable-giveaway-frontend validation
    uses: ./.github/workflows/verifiable-giveaway-frontend-ci.yaml

