name: Pull Request validation

on: [pull_request]


jobs:
  verifiable-shuffle-contracts-ci:
    if: '! github.event.pull_request.draft'
    name: Run verifiable-shuffle-contracts validation
    uses: ./.github/workflows/verifiable-shuffle-contracts-ci.yaml
