name: Validate verifiable-giveaway-frontend

on:
  
  workflow_call:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: verifiable-giveaway-frontend

jobs:
  validate:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokit
        run: pipx install algokit

      - name: Install dependencies
        run: algokit project bootstrap all --project-name 'verifiable-giveaway-frontend'

      
      - name: Run linters
        run: algokit project run lint --project-name 'verifiable-giveaway-frontend'
      
      
      - name: Run unit tests
        run: algokit project run test --project-name 'verifiable-giveaway-frontend'
      

      - name: Log in to the Container registry
        uses: docker/login-action@3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - name: Build and push Docker image
        uses: docker/build-push-action@5
        with:
          context: projects/verifiable-giveaway-frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
